Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Total entre dois números quaisquer
// Autor(a)    : Donisete Schwanck Lumertz
// Data atual  : 18/03/2020

Var
 n_1,n_2,X:real


Inicio

 escreval("Total entre dois números quaisquer")
escreva ("Digite um Número:")
leia(n_1)
escreva("Digite outro Número:")
leia(n_2)
X <- (n_1+n_2)
escreva ("Total =",X)


Fimalgoritmo